package words

func init() {
	registry["el"] = WordList{
		Adjectives: []string{
			"agios", "aktos", "alios", "anthos", "argos",
			"axios", "chromos", "demos", "dikaios", "dynatos",
			"efkeros", "eidos", "eklektos", "eleftheros", "endoxos",
			"evgenios", "evtychos", "gorgos", "helios", "ieros",
			"ikanios", "isios", "kairos", "kalos", "katharos",
			"koinos", "krateros", "kyrios", "lampros", "leukos",
			"logios", "makarios", "megas", "mikros", "monos",
			"morphos", "neos", "oxys", "palaios", "pantos",
			"pistos", "platys", "protos", "pyknos", "semnos",
			"sofos", "stenos", "synetos", "tachos", "thermos",
			"timios", "tycheros", "zestos", "zoros", "akribis",
			"alithinos", "amesos", "anetos", "aplos", "armonikos",
			"avtarkis", "axioprepes", "deksios", "dokimos", "eftychos",
			"enkardios", "entimos", "epifanis", "eriktos", "eternos",
			"evdokimos", "evlavis", "evnoikos", "evtolmos", "galinos",
			"gigantos", "glykos", "gnisios", "gymnos", "harmonios",
			"hedyos", "ikaios", "isovios", "kallistos", "lamprotatos",
			"megalos", "niktios", "olympios", "panisxiros", "perifanos",
			"pneumatikos", "politimos", "proodos", "simantos", "skyros",
			"taktikos", "thavmasios", "timioros", "vathys", "zontanos",
		},
		Nouns: []string{
			"agapi", "aeras", "agora", "akti", "aloni",
			"anthimos", "arki", "asteri", "chara", "chronia",
			"chrysos", "dasos", "drakon", "dromos", "dynami",
			"elpida", "eros", "faros", "fengari", "fotia",
			"galatia", "gata", "geitonas", "glossa", "helios",
			"himona", "hippos", "hydra", "kairos", "kardia",
			"kastro", "keras", "kipos", "kolpos", "kosmos",
			"kratos", "kyma", "lagos", "laos", "leo",
			"limani", "logos", "lykos", "melissi", "moira",
			"mythos", "nefos", "neros", "nixta", "notos",
			"okeanos", "onoma", "orama", "oros", "ouranos",
			"paidi", "paradeisos", "pateras", "pegasos", "petros",
			"phoenix", "poli", "potami", "pyxis", "riza",
			"rodo", "selini", "sfaira", "simaia", "sofia",
			"spiti", "stavros", "stoli", "synora", "taxidi",
			"theos", "thyra", "timis", "topos", "tragos",
			"tromos", "tychi", "velos", "vouno", "alsos",
			"antron", "demos", "ergon", "gaia", "kaima",
			"klima", "klios", "krini", "limos", "nisi",
			"oksos", "orki", "pelagos", "petra", "polemos",
		},
	}
}
