package words

func init() {
	registry["en"] = WordList{
		Adjectives: []string{
			"happy", "bright", "calm", "brave", "eager",
			"fancy", "jolly", "kind", "lively", "merry",
			"neat", "proud", "quick", "sharp", "smart",
			"swift", "tidy", "warm", "witty", "bold",
			"cool", "daring", "dazzling", "fair", "fierce",
			"gentle", "grand", "great", "humble", "ideal",
			"keen", "lofty", "lucky", "mighty", "noble",
			"peppy", "plain", "polite", "pure", "quiet",
			"rapid", "rare", "ready", "rich", "royal",
			"safe", "sleek", "slim", "smooth", "solid",
			"sunny", "super", "sweet", "tall", "tough",
			"true", "unique", "upbeat", "vast", "vibrant",
			"vivid", "wonderful", "worthy", "young", "zany",
			"zealous", "agile", "airy", "alert", "alive",
			"amazing", "ample", "ancient", "artful", "astute",
			"athletic", "atomic", "audacious", "aware", "balanced",
			"blazing", "blissful", "blooming", "bouncy", "capable",
			"careful", "charming", "cheerful", "clever", "cozy",
			"crisp", "curious", "deft", "dynamic", "earnest",
			"elegant", "energetic", "faithful", "fearless", "focused",
		},
		Nouns: []string{
			"river", "mountain", "forest", "ocean", "valley",
			"cloud", "storm", "breeze", "flame", "stone",
			"eagle", "falcon", "panda", "tiger", "wolf",
			"lion", "bear", "fox", "hawk", "owl",
			"star", "moon", "sun", "comet", "planet",
			"bridge", "castle", "tower", "garden", "field",
			"cabin", "island", "harbor", "canyon", "desert",
			"glacier", "meadow", "reef", "marsh", "delta",
			"crystal", "ember", "frost", "gale", "haze",
			"mist", "peak", "ridge", "surge", "tide",
			"anchor", "arrow", "beacon", "blade", "crown",
			"dagger", "forge", "gem", "globe", "hammer",
			"helm", "key", "lantern", "lens", "mirror",
			"needle", "orb", "prism", "quest", "rune",
			"sage", "seal", "shield", "sigil", "spark",
			"spirit", "tome", "trail", "vault", "wave",
			"wind", "wing", "zenith", "apex", "arch",
			"atom", "axis", "bolt", "bond", "byte",
			"cache", "chain", "cipher", "circuit", "code",
			"core", "crest", "drift", "flare", "grove",
		},
	}
}
