package words

func init() {
	registry["es"] = WordList{
		Adjectives: []string{
			"agil", "alegre", "amable", "amplio", "antiguo",
			"arrojado", "astuto", "audaz", "bello", "brillante",
			"bueno", "calido", "capaz", "cauto", "celeste",
			"certero", "claro", "constante", "cordial", "correcto",
			"curioso", "decente", "diestro", "digno", "directo",
			"eficaz", "elegante", "energico", "epico", "estable",
			"exacto", "excelso", "fiel", "firme", "flexible",
			"fluido", "franco", "fresco", "fuerte", "generoso",
			"grato", "habil", "heroico", "honesto", "ideal",
			"ilustre", "ingenioso", "intrepido", "jovial", "justo",
			"leal", "listo", "logico", "lucido", "magnifico",
			"manso", "noble", "nuevo", "optimo", "ordenado",
			"osado", "paciente", "pleno", "poderoso", "puro",
			"rapido", "recto", "refinado", "regio", "robusto",
			"sagaz", "sabio", "seguro", "sereno", "sincero",
			"solido", "supremo", "templado", "tenaz", "tranquilo",
			"unico", "util", "valiente", "veloz", "veraz",
			"vibrante", "vigoroso", "virtuoso", "vivo", "acertado",
			"activo", "afable", "certero", "dichoso", "docil",
			"duradero", "esbelto", "fertil", "glorioso", "lozano",
		},
		Nouns: []string{
			"aguila", "alba", "alcazar", "aldea", "arbol",
			"arco", "arena", "arroyo", "astro", "ave",
			"bosque", "brisa", "bruma", "caballo", "camino",
			"campo", "cascada", "castillo", "cerro", "cielo",
			"ciudad", "colina", "copa", "coral", "corona",
			"cumbre", "delfin", "destino", "dragon", "emblema",
			"espada", "estrella", "faro", "flecha", "flor",
			"fuego", "glaciar", "golfo", "guardia", "halcon",
			"heroe", "horizonte", "isla", "jardin", "lago",
			"lanza", "leon", "llama", "llave", "lobo",
			"luna", "luz", "mar", "marea", "monte",
			"noche", "nube", "oceano", "ola", "orbe",
			"paloma", "pico", "piedra", "planeta", "pluma",
			"prisma", "puente", "rayo", "roca", "ruta",
			"sabana", "selva", "sendero", "sierra", "signo",
			"sol", "tormenta", "torrente", "trueno", "valle",
			"vela", "viento", "vista", "volcan", "vuelo",
			"zafiro", "abismo", "alborada", "bahia", "brecha",
			"calma", "cima", "claro", "corriente", "desfiladero",
			"duende", "estuario", "fiordo", "lecho", "nebulosa",
		},
	}
}
