package words

func init() {
	registry["it"] = WordList{
		Adjectives: []string{
			"agile", "allegro", "ampio", "antico", "ardito",
			"arguto", "astuto", "audace", "bello", "bravo",
			"brillante", "buono", "caldo", "calmo", "capace",
			"cauto", "celeste", "chiaro", "costante", "cortese",
			"corretto", "curioso", "decente", "destro", "degno",
			"diretto", "docile", "durevole", "efficace", "elegante",
			"energico", "epico", "esatto", "fermo", "fiero",
			"fluido", "forte", "franco", "fresco", "generoso",
			"grato", "grande", "giovane", "abile", "ideale",
			"illustre", "ingegnoso", "intrepido", "leale", "lesto",
			"logico", "lucido", "magnifico", "maestoso", "mite",
			"nobile", "nuovo", "ottimo", "ordinato", "paziente",
			"pieno", "potente", "puro", "rapido", "retto",
			"raffinato", "regio", "robusto", "saggio", "sagace",
			"sicuro", "sereno", "sincero", "solido", "supremo",
			"tenace", "tranquillo", "unico", "utile", "valente",
			"veloce", "verace", "vibrante", "vigoroso", "virtuoso",
			"vivo", "zelante", "attento", "caparbio", "dinamico",
			"eccelso", "fedele", "giocoso", "leggero", "moderno",
			"preciso", "profondo", "radioso", "resiliente", "spontaneo",
		},
		Nouns: []string{
			"aquila", "alba", "albero", "arco", "arena",
			"astro", "bosco", "brezza", "bruma", "cavallo",
			"cammino", "campo", "canzone", "cascata", "castello",
			"collina", "cometa", "corona", "corallo", "cima",
			"cielo", "cristallo", "delfino", "destino", "drago",
			"emblema", "spada", "stella", "faro", "freccia",
			"fiore", "forza", "fuoco", "ghiaccio", "golfo",
			"guardia", "falco", "eroe", "orizzonte", "isola",
			"giardino", "lago", "lancia", "leone", "fiamma",
			"chiave", "lupo", "luna", "luce", "mare",
			"marea", "monte", "notte", "nuvola", "oceano",
			"onda", "orbe", "colomba", "picco", "pietra",
			"pino", "pianeta", "piuma", "prisma", "ponte",
			"raggio", "roccia", "savana", "selva", "sentiero",
			"segno", "sole", "tempesta", "torrente", "tuono",
			"valle", "vela", "vento", "vista", "vulcano",
			"volo", "zaffiro", "arcobaleno", "baia", "caldera",
			"duna", "estuario", "fiordo", "grotta", "laguna",
			"nebbia", "palude", "penisola", "pianura", "porto",
			"spiaggia", "abisso", "burrasca", "crepuscolo", "foresta",
		},
	}
}
