package words

func init() {
	registry["pl"] = WordList{
		Adjectives: []string{
			"aktywny", "bystry", "celny", "cichy", "ciekawy",
			"czysty", "daleki", "dobry", "dokladny", "doskonaly",
			"duzy", "dzielny", "elegancki", "fantastyczny", "gorliwy",
			"gotowy", "hardy", "hojny", "idealny", "inteligentny",
			"jasny", "jedyny", "klasyczny", "kluczowy", "kompetentny",
			"korzystny", "krotki", "lekki", "logiczny", "lojalny",
			"lotny", "lubiany", "ladny", "madry", "majestatyczny",
			"maly", "mily", "mocny", "niezwykly", "niezlomny",
			"nowy", "odwazny", "ogromny", "otwarty", "pewny",
			"pilny", "plastyczny", "plodny", "pokorny", "potezny",
			"prawy", "precyzyjny", "prosty", "radosny", "rzetelny",
			"slawny", "smukly", "solidny", "spokojny", "sprawny",
			"staly", "stalowy", "szybki", "szlachetny", "smialy",
			"swietny", "twardy", "uparty", "wierny", "wielki",
			"wolny", "wspanialy", "wytrzymaly", "zaradny", "zdrowy",
			"zreczny", "zwinny", "zywotny", "zwiezly", "znakomity",
			"akademicki", "artystyczny", "ceniony", "czolowy", "delikatny",
			"energiczny", "fachowy", "gienny", "harmonijny", "inicjatywny",
			"junacki", "karny", "liryczny", "mistrzowski", "natchniony",
			"odporny", "pelny", "rozlegly", "skuteczny", "tworczy",
		},
		Nouns: []string{
			"chmura", "czas", "dab", "deszcz", "dolina",
			"dom", "droga", "drzewo", "dym", "dzien",
			"echo", "fala", "glos", "gory", "grad",
			"grom", "gwiazda", "jar", "jezioro", "jesien",
			"kamien", "klif", "korona", "kraj", "ksiezyc",
			"las", "lew", "lodowiec", "luk", "lowca",
			"miasto", "mgla", "morze", "most", "natura",
			"noc", "niebo", "ogien", "okean", "orzel",
			"pagoda", "pantera", "pik", "planeta", "potok",
			"przygoda", "rzeka", "ryba", "skala", "slonce",
			"smok", "sokol", "sowa", "szlak", "tarcza",
			"twierdza", "tygrys", "wiatr", "wiek", "wies",
			"wilk", "woda", "wojownik", "wyspa", "zamek",
			"zenit", "zima", "znak", "zorza", "zrodlo",
			"zeglarz", "bohater", "brama", "duch", "element",
			"iskra", "klan", "laguna", "meteor", "miecz",
			"oblok", "abysm", "burza", "cwiczenie", "delta",
			"fiord", "glaz", "harfa", "iglica", "jaskinia",
			"klucz", "lotnik", "mrok", "nurt", "ostep",
			"powiew", "rejs", "strumien", "tuman", "wicher",
		},
	}
}
