package words

func init() {
	registry["pt"] = WordList{
		Adjectives: []string{
			"agil", "alegre", "amplo", "antigo", "ardente",
			"arguto", "astuto", "audaz", "belo", "brilhante",
			"bom", "calmo", "capaz", "cauto", "celeste",
			"certo", "claro", "confiante", "constante", "correto",
			"cortez", "curioso", "decente", "destro", "digno",
			"direto", "eficaz", "elegante", "energico", "epico",
			"estavel", "exato", "feroz", "firme", "flexivel",
			"fluido", "forte", "franco", "fresco", "generoso",
			"grato", "grande", "jovem", "ideal", "ilustre",
			"ingenioso", "intrepido", "leal", "lesto", "logico",
			"lucido", "magnifico", "majestoso", "manso", "nobre",
			"novo", "otimo", "ordenado", "ousado", "paciente",
			"pleno", "poderoso", "puro", "rapido", "reto",
			"refinado", "regio", "robusto", "sagaz", "sabio",
			"seguro", "sereno", "sincero", "solido", "supremo",
			"tenaz", "tranquilo", "unico", "util", "valente",
			"veloz", "veraz", "vibrante", "vigoroso", "virtuoso",
			"vivo", "zeloso", "atento", "caprichoso", "determinado",
			"equilibrado", "fiel", "glorioso", "harmonioso", "lindo",
			"moderno", "preciso", "profundo", "radiante", "resiliente",
		},
		Nouns: []string{
			"aguia", "alba", "arvore", "arco", "areia",
			"astro", "bosque", "brisa", "bruma", "cavalo",
			"caminho", "campo", "cascata", "castelo", "colina",
			"cometa", "coroa", "coral", "cume", "ceu",
			"cidade", "cristal", "golfinho", "destino", "dragao",
			"emblema", "espada", "estrela", "farol", "flecha",
			"flor", "forca", "fogo", "gelo", "golfo",
			"guarda", "falcao", "heroi", "horizonte", "ilha",
			"jardim", "lago", "lanca", "leao", "chama",
			"chave", "lobo", "lua", "luz", "mar",
			"mare", "monte", "noite", "nuvem", "oceano",
			"onda", "orbe", "pomba", "pico", "pedra",
			"pinheiro", "planeta", "pena", "prisma", "ponte",
			"raio", "rocha", "rota", "savana", "selva",
			"trilha", "sinal", "sol", "tempestade", "torrente",
			"trovao", "vale", "vela", "vento", "vista",
			"vulcao", "voo", "safira", "baia", "caldeira",
			"duna", "estuario", "fiorde", "gruta", "laguna",
			"neblina", "pantano", "peninsula", "planicie", "porto",
			"praia", "abismo", "cancao", "crepusculo", "floresta",
		},
	}
}
